### ISSUE TITLE
1. [Reading] Ansible fundamentals

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/event-driven-architecture#12]
Go through a resource below (feel free to add any good ones you find).

- https://www.redhat.com/en/topics/automation/learning-ansible-tutorial.
- Intro chapters from book @ChrOertlin shared in Slack channel.

**Comment by seallard** [comment]
done

**Comment by islean** [comment]
done

**Comment by diitaz93** [comment]
Done ✅ 
What I got from it:
The **playbook** is a YAML file describing the state of the configuration of a server. It has several **tasks**, which are individual configuration changes. Each task runs a **module** which is a script.
You can run a playbook in a "dry-run" mode.
When running a playbook, it determines which parts of the server configuration differ from the playbook and runs those tasks (in the order in which they were written). This is how idempotency is achieved.
