### ISSUE TITLE
Determine key considerations when selecting a messaging platform

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/event-driven-architecture#16]
What are the most important aspects of the platform? What aspects of it should be considered?
Use case: basic pub/sub pattern.
Scale: small, < 1 million events/month long term.
Hosting: on-prem

**Comment by seallard** [comment]
- Pricing
- Possibility to host on-prem
- Complexity in  setup and maintenance
- Reliability in operation
- Long term stability
- Existing Python clients

**Comment by samuell** [comment]
Some suggestions for apsects to consider:

- Ease of monitor and debugging
- Ease of adding new components and pipelines
- Ease of resolving data inconsistencies manually/semi-manually

**Comment by seallard** [comment]
For delivery guarantees, I think we should go for least-once guarantees and ensure that each event processing is idempotent.

**Comment by seallard** [comment]
What we need
- Cost: preferably free
- Hosting: on-prem.
- Operational Complexity: easy setup and maintenance.
- Reliability in Operation: Uptime, fault tolerance, redundancy.
- Long Term Stability: mature, certain to be around for a long time.
- Ease of Integration: need existing Python clients.
- Supports Pub/Sub
- Delivery Guarantees: At-most-once, at-least-once, exactly-once delivery. We can shape the architecture to fit any of these.
- Ordering: We would likely benefit from being able to guarantee message order.
- Persistence: Need persistence of messages for DLQ or if broker/consumer goes down.
- Observability: need to be possible to integrate with some monitoring solution.

**Comment by seallard** [comment]
Lets say we have 10 asynchronous steps in our flow (we should map this out more clearly, but sequencing, demultiplexing, sequencing qc, post processing, fabricating jobs, collecting results, qc on results, uploading results).

Lets say we process 1000 cases per month.

Then our load would be, assuming each step publishes events per case, at the minimum 10 000 events. That is nothing.
