### ISSUE TITLE
Research existing messaging platforms

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/event-driven-architecture#17]
What are our options?

**Comment by seallard** [comment]
- Kafka
- Confluent Kafka
- Pulsar
- StackStorm
- Cadence
- Temporal
- RabbitMQ
- Redis Pub/Sub
- Amazon SNS & SQS
- Google Pub/Sub
- Azure Service Bus
- NATS

**Comment by samuell** [comment]
- [Apache Beam](https://beam.apache.org/) - (Seems to have a pretty conflated programming API though, IMO)
