### ISSUE TITLE
Evaluate options

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/event-driven-architecture#18]
Based on the criteria documented in https://github.com/Clinical-Genomics/event-driven-architecture/issues/16, evaluate the options identified in https://github.com/Clinical-Genomics/event-driven-architecture/issues/17

**Comment by seallard** [comment]
| Platform             | Pricing | On-Prem Hosting | Complexity | Reliability | Stability | Python Clients | Pub/Sub Support | Ext. Sys. Integration | Documentation | Delivery Guarantees      | Monitoring | Persistence |
|----------------------|---------|-----------------|------------|-------------|-----------|----------------|-----------------|-----------------------|---------------|--------------------------|------------|-------------|
| Kafka                | Free    | Yes             | Medium     | High        | High      | Yes            | Yes             | Yes                   | Excellent     | At least once, Exactly once | Good       | Yes         |
| Confluent Kafka      | Paid    | Yes             | Medium     | High        | High      | Yes            | Yes             | Yes                   | Excellent     | At least once, Exactly once | Excellent  | Yes         |
| Pulsar               | Free    | Yes             | High       | High        | High      | Yes            | Yes             | Yes                   | Good          | At least once, Exactly once | Good       | Yes         |
| StackStorm           | Free    | Yes             | High       | Medium      | Medium    | Yes            | Yes             | Yes                   | Moderate      | At least once             | Good       | Yes         |
| Cadence              | Free    | Yes             | High       | Medium      | Medium    | Yes            | No              | Yes                   | Good          | At least once             | Good       | Yes         |
| Temporal             | Free    | Yes             | Medium     | High        | High      | Yes            | No              | Yes                   | Good          | At least once             | Good       | Yes         |
| RabbitMQ             | Free    | Yes             | Low        | High        | High      | Yes            | Yes             | Yes                   | Excellent     | At least once, Exactly once | Excellent  | Yes         |
| Redis Pub/Sub        | Free    | Yes             | Low        | High        | High      | Yes            | Yes             | Yes                   | Excellent     | At most once              | Limited    | No          |
| Google Pub/Sub       | Paid    | No              | Low        | High        | High      | Yes            | Yes             | Yes                   | Excellent     | At least once, Exactly once | Excellent  | Yes         |
| Azure Service Bus    | Paid    | No              | Low        | High        | High      | Yes            | Yes             | Yes                   | Excellent     | At least once, Exactly once | Excellent  | Yes         |
| NATS                 | Free    | Yes             | Medium     | High        | High      | Yes            | Yes             | Yes                   | Good          | At most once, At least once | Good       | Yes         |
| Kinesis              | Paid    | No              | Low        | High        | High      | Yes            | Yes             | Yes                   | Excellent     | At least once, Exactly once | Excellent  | Yes         |
| AWS SNS              | Paid    | No              | Low        | High        | High      | Yes            | Yes             | Yes                   | Excellent     | At least once             | Excellent  | Yes         |
| AWS SQS              | Paid    | No              | Low        | High        | High      | Yes            | Yes             | Yes                   | Excellent     | At least once, Exactly once | Excellent  | Yes         |
| MSK                  | Paid    | Yes             | Medium     | High        | High      | Yes            | Yes             | Yes                   | Excellent     | At least once, Exactly once | Excellent  | Yes         |
| Redpanda             | Free    | Yes             | Medium     | High        | High      | Yes            | Yes             | Yes                   | Good          | At least once, Exactly once | Good       | Yes         |
| Liftbridge           | Free    | Yes             | Medium     | High        | High      | Yes            | Yes             | Yes                   | Moderate      | At least once             | Good       | Yes         |
| ActiveMQ             | Free    | Yes             | Medium     | High        | High      | Yes            | Yes             | Yes                   | Good          | At least once, Exactly once | Good       | Yes         |
| MQTT                 | Free    | Yes             | Low        | Medium      | Medium    | Yes            | Yes             | Yes                   | Good          | At most once, At least once | Good       | Yes         |
| Dapr                 | Free    | Yes             | High       | Medium      | Medium    | Yes            | Yes             | Yes                   | Good          | At least once, Exactly once | Good       | Yes         |
| Beam                 | Free    | Yes             | High       | Medium      | Medium    | Yes            | Yes             | Yes                   | Moderate      | At least once             | Good       | Yes         |

**Comment by seallard** [comment]
- Kafka ❌ - too complex to manage long term
- Confluent Kafka ❌ - too expensive
- Pulsar ❌ - too complex to manage long term
- StackStorm  ❌ - does not fit our use case, it is a workflow orchestration tool
- Cadence
- Temporal
- RabbitMQ
- Redis Pub/Sub
- Google Pub/Sub
- Azure Service Bus ❌ - cloud only
- NATS
- Kinesis
- AWS SNS ❌ - cloud only
- AWS SQS ❌ - cloud only
- MSK ❌ - cloud only
- redpanda
- liftbridge
- ActiveMQ
- MQTT
- Dapr
- Beam
- NATS Jetstream
- Watermill

**Comment by ChrOertlin** [comment]
Redis: https://www.openlogic.com/blog/apache-kafka-vs-redis#:~:text=Kafka%20is%20an%20open%20source,functions%20within%20application%20data%20infrastructure.

**Comment by ChrOertlin** [comment]
ActiveMQ: https://activemq.apache.org/
RabbitMQ: https://www.rabbitmq.com/

**Comment by islean** [comment]
Adding kafka-python: https://kafka-python.readthedocs.io/en/master/index.html

**Comment by seallard** [comment]
> Adding kafka-python: https://kafka-python.readthedocs.io/en/master/index.html

That is a Python client for the Kafka messaging platform. We are evaluating messaging platforms, not clients (even though we want whatever platform we pick to have a well maintained python client).

**Comment by seallard** [comment]
A useful comparison of Kafka, Pulsar and RabbitMQ https://www.confluent.io/kafka-vs-pulsar/

"""
Which to choose should be a fairly straightforward decision: for lightweight messaging that requires request-response, queuing, and pub-sub RabbitMQ is well suited; Pulsar is really only for the brave at heart, but it may have a place in the future for those that require both queuing and event streaming in the same system; for event streaming use cases that require high throughput, scalability, and permanent message storage Kafka is the clear winner. To learn more, check out this blog post on [benchmarking Kafka, Pulsar, and RabbitMQ](https://www.confluent.io/blog/kafka-fastest-messaging-system).
"""

**Comment by seallard** [comment]
Settled on NATS
