### ISSUE TITLE
Step 1: Learn pub/sub messaging pattern

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/event-driven-architecture#3]
Go through at least two of the below resources.

## Resources
- https://learn.microsoft.com/en-us/azure/architecture/patterns/publisher-subscriber
- https://www.confluent.io/learn/publish-subscribe/
- https://learn.microsoft.com/en-us/azure/architecture/guide/architecture-styles/event-driven

**Comment by seallard** [comment]
Done ✅

**Comment by islean** [comment]
Done ✅

**Comment by diitaz93** [comment]
Done ✅

**Comment by seallard** [comment]
@Vince-janv @ChrOertlin any progress?

**Comment by ChrOertlin** [comment]
👍

**Comment by seallard** [comment]
Done 🥳
