### ISSUE TITLE
Step 2: Learn Kafka fundamentals

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/event-driven-architecture#5]
We need to have a good understanding of the following
- Producers and Consumers: How data is published and subscribed to in a Kafka system.
- Topics and Partitions: Organization of data within Kafka.
- Brokers and Clusters: Kafka's physical deployment and scalability mechanisms.

Kafka connect/Kafka Streams/ksqlDB are for more advanced use cases, but is worth familiarizing yourself with somewhat.

## Resources
- https://kafka.apache.org/intro
- https://www.confluent.io/blog/best-kafka-tutorials-examples-and-learning-resources/

**Comment by diitaz93** [comment]
This video explains it nicely https://youtu.be/B5j3uNBH8X4?feature=shared

**Comment by seallard** [comment]
> This video explains it nicely https://youtu.be/B5j3uNBH8X4?feature=shared

Yeah! The video after was good as well https://www.youtube.com/watch?v=jY02MB-sz8I&list=PLa7VYi0yPIH2PelhRHoFR5iQgflg-y6JA&index=5

**Comment by seallard** [comment]
Done ✅

**Comment by seallard** [comment]
Done? @diitaz93 @islean @ChrOertlin @islean?

**Comment by seallard** [comment]
Done ✅

**Comment by islean** [comment]
Done ✅

**Comment by diitaz93** [comment]
Done ✅

**Comment by seallard** [comment]
Done 🥳
